// Only visually reviewed, reusable full movement cycles belong here.
export const followMedia = [
  { id: 'lateral-raise', seconds: 4.04, cues: [{at: 0, text: 'ยกขึ้น'}, {at: 1.5, text: 'ค่อย ๆ ลดลง'}], author: 'Goulart · wger', source: 'https://wger.de/media/exercise-video/348/de69928a-8a35-4096-821c-1f46de5e0e03.MOV', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/', changes: 'ตัดช่วง 0.25–2.25 วินาที ลดความเร็วครึ่งหนึ่ง ย่อภาพและตัดเสียง ภาพที่ปรับและภาพปกใช้ CC BY-SA 4.0' },
{"id": "bodyweight-squat", "seconds": 4.08, "cues": [{"at": 0, "text": "ค่อย ๆ ย่อตัวลง"}, {"at": 2.4, "text": "ดันตัวขึ้น"}], "author": "Danielflefil · Wikimedia Commons", "source": "https://commons.wikimedia.org/wiki/File:Bodyweight_Squats.gif", "license": "CC BY-SA 4.0", "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/", "changes": "แปลง GIF เป็น MP4 ลดความเร็วเหลือสองในสาม ย่อภาพ ภาพที่ปรับและภาพปกใช้ CC BY-SA 4.0"},
{"id": "dumbbell-rdl", "seconds": 4.68, "cues": [{"at": 0, "text": "ดันสะโพกไปด้านหลัง"}, {"at": 3.25, "text": "ยืนขึ้นช้า ๆ"}], "author": "Capt. Matthew Holfinger · U.S. Marine Corps / DVIDS", "source": "https://www.dvidshub.net/video/548459/dumbbell-romanian-deadlift", "license": "Public domain (United States)", "licenseUrl": "https://www.dvidshub.net/about/copyright", "changes": "ตัดช่วง 19.9–24.5 วินาที ย่อภาพและตัดเสียง", "disclaimer": "The appearance of U.S. Department of War (DoW) visual information does not imply or constitute DoW endorsement."},
{"id": "wall-pushup", "seconds": 3.52, "cues": [{"at": 0, "text": "งอศอกเข้าหาผนัง"}, {"at": 2, "text": "ดันตัวออกจากผนัง"}], "author": "Centers for Disease Control and Prevention · Wikimedia Commons", "source": "https://commons.wikimedia.org/wiki/File:Wallpushup-CDC_strength_training_for_older_adults.gif", "license": "Public domain (United States)", "licenseUrl": "https://commons.wikimedia.org/wiki/File:Wallpushup-CDC_strength_training_for_older_adults.gif#Licensing", "changes": "ภาพวาดสาธิตของ CDC แปลง GIF เป็น MP4 หนึ่งรอบ คงจังหวะต้นฉบับ ไม่มีเสียง"},
{"id": "floor-press", "seconds": 6, "cues": [{"at": 0, "text": "ดันดัมเบลขึ้น"}, {"at": 1.5, "text": "คงท่า หายใจตามปกติ"}, {"at": 4.5, "text": "ค่อย ๆ ลดลงสู่พื้น"}], "author": "Centers for Disease Control and Prevention · Wikimedia Commons", "source": "https://commons.wikimedia.org/wiki/File:Chest_press-CDC_strength_training_for_older_adults.gif", "license": "Public domain (United States)", "licenseUrl": "https://commons.wikimedia.org/wiki/File:Chest_press-CDC_strength_training_for_older_adults.gif#Licensing", "changes": "ภาพวาดสาธิตดันอกบนพื้นของ CDC แปลง GIF เป็น MP4 หนึ่งรอบ คงจังหวะต้นฉบับ เพิ่มขอบขาว 1 พิกเซล ไม่มีเสียง"},
{"id": "dumbbell-row", "seconds": 4.52, "cues": [{"at": 0, "text": "ดึงศอกไปด้านหลัง"}, {"at": 2.1, "text": "ค่อย ๆ ลดแขนลง"}], "author": "Capt. Matthew Holfinger · U.S. Marine Corps / DVIDS", "source": "https://www.dvidshub.net/video/636921/dumbbell-bent-over-rows", "license": "Public domain (United States)", "licenseUrl": "https://www.dvidshub.net/about/copyright", "changes": "ตัดช่วง 7.05–8.55 วินาที เลือกภาพมุมด้านข้างจากครึ่งล่าง ลดความเร็วเหลือหนึ่งในสามและตัดเสียง", "disclaimer": "The appearance of U.S. Department of War (DoW) visual information does not imply or constitute DoW endorsement."},
];
export const getFollowMedia = id => followMedia.find(media => media.id === id);
export const hasFollowMedia = id => Boolean(getFollowMedia(id));
